### ISSUE TITLE
Unable to completely remove Servers with Credentials

### ISSUE THREAD

**Issue by dcbrundage** [jamf/jamf-printer-manager#3]
Unable to remove stored server with login credentials.  I have two accounts for one Jamf server and every time I open Jamf Print Manager it defaults to the account I do not want to use.

I have removed the Jamf Print Manager from Applications as well as ~/Library/Containers/com.jamf.ce.printermanager and the keychain entry which starts with "JSK-".

When I add the Jamf Print Manager application to the Application folder again the stored servers & creds are still there.

Is there another method to reset the stored servers & creds?

**Comment by DCBrundage-UCAR** [comment]
Thanks Leslie!! 1.0.2 works much better with the saved servers & creds. I really appreciate your help.

**Comment by dcbrundage** [comment]
Thanks Leslie!! 1.0.2 works much better with the saved servers & creds. I really appreciate your help.
